apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-recorder
spec:
  replicas: 2
  selector:
    matchLabels:
      de-app: event-recorder
  template:
    metadata:
      labels:
        de-app: event-recorder
    spec:
      restartPolicy: Always
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
        - name: timezone
          configMap:
            name: timezone
            items:
              - key: timezone
                path: timezone
        - name: service-configs
          secret:
            secretName: service-configs
            items:
              - key: jobservices.yml
                path: jobservices.yml
      containers:
        - name: event-recorder
          image: discoenv/event-recorder
          resources:
            event-recorder:
              cpu: "1m"
              memory: "128Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
          args:
            - --config
            - /etc/iplant/de/jobservices.yml
          volumeMounts:
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
            - name: timezone
              mountPath: /etc/timezone
              subPath: timezone
            - name: service-configs
              mountPath: /etc/iplant/de
              readOnly: true
